---
title: "phenoflex"
author: "Erica Kirchhof"
date: "2025-11-20"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r PhenoFlex fitting and evaluation - runs independent from other code}


#### load packages and datasets ####
library(rstudioapi)
library(dplyr)
library(chillR)
library(lubridate)
library(purrr)
library(ggplot2)

setwd(dirname(getActiveDocumentContext()$path)) 

#### Prepare overall weather data ####

wdat=read.csv("VitisPhenology_PhenoFlex_data_weather.csv") 

wdat$date=paste(wdat$day, "-",wdat$month, "-", wdat$year)
wdat$date=gsub(' ','',wdat$date)
wdat$date=as.Date(wdat$date, format="%d-%m-%Y")

wdat$Dataset=paste((as.numeric(year(wdat$date))-1),as.numeric(year(wdat$date)),sep="-" )

wdat$Dataset[month(wdat$date)>7]=paste((as.numeric(year(wdat$date[month(wdat$date)>7]))),(as.numeric(year(wdat$date[month(wdat$date)>7]))+1),sep="-" )

wdat$Dataset=as.factor(wdat$Dataset)
wdat$Location=as.factor(wdat$Location)

wdat$Location=factor(wdat$Location)
levels(wdat$Location)


locdat=read.csv("VitisPhenology_PhenoFlex_data_locations.csv")
locdat$Location=factor(locdat$Location)


wdat2=merge(wdat,locdat)

colnames(wdat2)=c("Location","Date","Tmin","Tmax","yday","Year","Month","Day","Dataset",
                  "Latitude","Location2","Country")

wdat3=NULL

for (j in levels(wdat2$Location)) {

  datc=subset(wdat2, Location %in% j)
  datc$Dataset=factor(datc$Dataset)

for (i in levels(datc$Dataset)) {

  datb=subset(datc, Dataset %in% i)

  if (nrow(datb)>300) {

  hourly=data.frame(stack_hourly_temps(weather=datb,latitude=mean(datb$Latitude)))

  colnames(hourly)=c("Location","Date","Tmin","Tmax","yday","Year","Month","Day","Dataset",
                  "Latitude","Location2","Country","JDay","Hour","Temperature","QC")

  wdat3=rbind(wdat3,hourly)

  print(c(i,j))
  }
}}

wdat3store=wdat3


wdat3$Location2=factor(wdat3$Location2)
wdat3$Country=factor(wdat3$Country)

#### Load budbreak data ####

bbdat=read.csv("VitisPhenology_PhenoFlex_data_budbreak.csv", stringsAsFactors = T)

bbdat$Dataset=factor(paste((bbdat$Year-1),bbdat$Year,sep="-"))
bbdat$Cultivar=factor(bbdat$Cultivar)
bbdat$Location=factor(bbdat$Location)

```


```{r CAB SAUV FITTING AND VALIDATION Model 1}

#### Extracting Phenology datasets #####

Bergheim_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Colmar",
BBCH.scale %in% c(7,NA),
Cultivar == "Cabernet_Sauvignon") %>% arrange(Year)

pheno_years_Bergheim <- unique(Bergheim_pheno$Year)


Vassal_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Vassal",
BBCH.scale %in% c(7,NA),
Cultivar == "Cabernet_Sauvignon") %>% arrange(Location, Year)

pheno_years_Vassal <- unique(Vassal_pheno$Year)


MB_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "MB",
BBCH.scale %in% c(7,NA),
Cultivar == "Cabernet_Sauvignon") %>% arrange(Location, Year)

pheno_years_MB <- unique(MB_pheno$Year)

Bordeaux_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Bordeaux",
BBCH.scale %in% c(7,NA),
Cultivar == "Cabernet_Sauvignon") %>% arrange(Location, Year)

pheno_years_Bordeaux <- unique(Bordeaux_pheno$Year)


#### Prepare temperature datasets ####

wdat.Bergheim <- subset(wdat2, Location %in% "Colmar")
wdat.Bergheim <- droplevels(wdat.Bergheim)


Bergheim_easy <- data.frame(wdat.Bergheim) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Bergheim)


wdat.Vassal <- subset(wdat2, Location %in% "Vassal")
wdat.Vassal <- droplevels(wdat.Vassal)

Vassal_easy <- data.frame(wdat.Vassal) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Vassal)


wdat.MB <- subset(wdat2, Location %in% "MB")
wdat.MB <- droplevels(wdat.MB)

MB_easy <- data.frame(wdat.MB) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_MB)

wdat.Bordeaux <- subset(wdat2, Location %in% "Bordeaux")
wdat.Bordeaux <- droplevels(wdat.Bordeaux)

Bordeaux_easy <- data.frame(wdat.Bordeaux) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Bordeaux)



#### parameterize phenoflex w Bergheim data ####

upper <- c(42, 200, 1.0, 30, 4000.0, 10000.0, 7000.0, 6.e13, 10, 40, 10, 50.00)
lower <- c(39, 180, 0.1, 0 , 3000.0, 9000.0, 6000.0, 5.e13, 0, 0, 0, 0.05)

CS_model1=data.frame(NULL)

# This for loop can be skipped as the optimized parameters from the 30 iterations are fit again afterwards.
# 
# for (i in 1:30) {
# 
#   set.seed(i)
# 
#   Fit_res_CS <- phenologyFitter(
#   modelfn = PhenoFlex_GDHwrapper,
#   bloomJDays = Bergheim_pheno$pheno,
#   SeasonList = Bergheim_easy,
#   lower = lower,
#   upper = upper,
#   control = list(
#   smooth = FALSE,
#   verbose = TRUE,
#   maxit = 30,
#   nb.stop.improvement = 500
#   )
#   )
# 
#   Fit_res_CS$model_fit$par
# 
# 
#   Bergheim_pheno$predicted <-
#   purrr::map_dbl(Bergheim_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
#   Bergheim_pheno$val <- 0
#   RMSEP(Bergheim_pheno$predicted, Bergheim_pheno$pheno, na.rm = T)
# 
# 
#   # validation procedure, MB and Bordeaux #
#   Vassal_pheno$predicted <-
#   purrr::map_dbl(Vassal_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
#   Vassal_pheno$val <- 1
# 
# 
#   MB_pheno$predicted <-
#   purrr::map_dbl(MB_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
#   MB_pheno$val <- 1
# 
#   Bordeaux_pheno$predicted <-
#   purrr::map_dbl(Bordeaux_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
#   Bordeaux_pheno$val <- 1
# 
#   #RMSEP(Vassal_pheno$predicted, Vassal_pheno$pheno, na.rm = T)
# 
#   #RMSEP(MB_pheno$predicted, MB_pheno$pheno, na.rm = T)
# 
#   #RMSEP(Bordeaux_pheno$predicted, Bordeaux_pheno$pheno, na.rm = T)
# 
# 
#   cabsauv_pheno <- rbind(Bergheim_pheno,
#                          Vassal_pheno,
#                          MB_pheno,
#                          Bordeaux_pheno)
#   a=RMSEP(cabsauv_pheno$predicted, cabsauv_pheno$pheno, na.rm = T)
# 
#   cabsauv_phenoval<- rbind(Vassal_pheno,
#                          MB_pheno,
#                          Bordeaux_pheno)
#   b=RMSEP(cabsauv_phenoval$predicted, cabsauv_phenoval$pheno, na.rm = T)
# 
#   c=RMSEP(Bergheim_pheno$predicted, Bergheim_pheno$pheno, na.rm = T)
# 
#   CS_model1=rbind(CS_model1, c(i, a, b, c))
#   print(i)
# 
# }
# 
# colnames(CS_model1)=c("seed","RMSEall","RMSEval","RMSEcal")

# seed 25 produces lowest RMSEall = 7.12; RMSEval = 7.81; RMSEcal=5.79

set.seed(25)
    
Fit_res_CS <- phenologyFitter(
modelfn = PhenoFlex_GDHwrapper,
bloomJDays = Bergheim_pheno$pheno,
SeasonList = Bergheim_easy,
lower = lower,
upper = upper,
control = list(
smooth = FALSE,
verbose = TRUE,
maxit = 30,
nb.stop.improvement = 500
)
)

Bergheim_pheno$predicted <-
purrr::map_dbl(Bergheim_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
Bergheim_pheno$val <- 0


# validation procedure, MB and Bordeaux #
Vassal_pheno$predicted <-
purrr::map_dbl(Vassal_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
Vassal_pheno$val <- 1


MB_pheno$predicted <-
purrr::map_dbl(MB_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
MB_pheno$val <- 1

Bordeaux_pheno$predicted <-
purrr::map_dbl(Bordeaux_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CS$model_fit$par))
Bordeaux_pheno$val <- 1



cabsauv_pheno <- rbind(Bergheim_pheno,
                       Vassal_pheno,
                       MB_pheno,
                       Bordeaux_pheno)
aCS=RMSEP(cabsauv_pheno$predicted, cabsauv_pheno$pheno, na.rm = T)

cabsauv_phenoval<- rbind(Vassal_pheno,
                       MB_pheno,
                       Bordeaux_pheno)
bCS=RMSEP(cabsauv_phenoval$predicted, cabsauv_phenoval$pheno, na.rm = T)

cCS=RMSEP(Bergheim_pheno$predicted, Bergheim_pheno$pheno, na.rm = T)

dCS=mean(cabsauv_pheno$predicted-cabsauv_pheno$pheno, na.rm = T)

eCS=mean(cabsauv_phenoval$predicted-cabsauv_phenoval$pheno, na.rm = T)

fCS=mean(Bergheim_pheno$predicted-Bergheim_pheno$pheno, na.rm = T)

aCS #RMSEall
bCS #RMSEval
cCS #RMSEcal

dCS #biasall
eCS #biasval
fCS #biascal


```



```{r RIESLING FITTING AND VALIDATION Model 1}
#### Extracting Phenology datasets #####

Bergheim_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Colmar",
BBCH.scale %in% c(7,NA),
Cultivar == "Riesling") %>% arrange(Year)

pheno_years_Bergheim <- unique(Bergheim_pheno$Year)


Bordeaux_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Bordeaux",
BBCH.scale %in% c(7,NA),
Cultivar == "Riesling") %>% arrange(Location, Year)

pheno_years_Bordeaux <- unique(Bordeaux_pheno$Year)

PA_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Lewisberg_PA",
BBCH.scale %in% c(7,NA),
Cultivar == "Riesling") %>% arrange(Location, Year)

pheno_years_PA<- unique(PA_pheno$Year)

LF_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Lower_Franconia",
BBCH.scale %in% c(7,NA),
Cultivar == "Riesling") %>% arrange(Location, Year)

pheno_years_LF <- unique(LF_pheno$Year)

MB_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "MB",
BBCH.scale %in% c(7,NA),
Cultivar == "Riesling") %>% arrange(Location, Year)

pheno_years_MB <- unique(MB_pheno$Year)

Ontario_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Ontario",
BBCH.scale %in% c(7,NA),
Cultivar == "Riesling") %>% arrange(Location, Year)

pheno_years_Ontario <- unique(Ontario_pheno$Year)

Vassal_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Vassal",
BBCH.scale %in% c(7,NA),
Cultivar == "Riesling") %>% arrange(Location, Year)

pheno_years_Vassal <- unique(Vassal_pheno$Year)


#### Prepare temperature datasets ####

wdat.Bergheim <- subset(wdat2, Location %in% "Colmar")
wdat.Bergheim <- droplevels(wdat.Bergheim)


Bergheim_easy <- data.frame(wdat.Bergheim) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Bergheim)

wdat.Bordeaux <- subset(wdat2, Location %in% "Bordeaux")
wdat.Bordeaux <- droplevels(wdat.Bordeaux)

Bordeaux_easy <- data.frame(wdat.Bordeaux) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Bordeaux)

wdat.PA <- subset(wdat2, Location %in% "Lewisberg_PA")
wdat.PA <- droplevels(wdat.PA)

PA_easy <- data.frame(wdat.PA) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_PA)

wdat.LF <- subset(wdat2, Location %in% "Lower_Franconia")
wdat.LF <- droplevels(wdat.LF)

LF_easy <- data.frame(wdat.LF) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_LF)

wdat.MB <- subset(wdat2, Location %in% "MB")
wdat.MB <- droplevels(wdat.MB)

MB_easy <- data.frame(wdat.MB) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_MB)

wdat.Ontario <- subset(wdat2, Location %in% "Ontario")
wdat.Ontario <- droplevels(wdat.Ontario)

Ontario_easy <- data.frame(wdat.Ontario) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Ontario)

wdat.Vassal <- subset(wdat2, Location %in% "Vassal")
wdat.Vassal <- droplevels(wdat.Vassal)

Vassal_easy <- data.frame(wdat.Vassal) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Vassal)


#### parameterize phenoflex w Bergheim data ####

upper <- c(42, 200, 1.0, 30, 4000.0, 10000.0, 7000.0, 6.e13, 10, 40, 10, 50.00)
lower <- c(39, 180, 0.1, 0 , 3000.0, 9000.0, 6000.0, 5.e13, 0, 0, 0, 0.05)


RIES_model1=data.frame(NULL)

# This for loop can be skipped as the optimized parameters from the 30 iterations are fit again afterwards.
# 
# for (i in 1:30) {
# 
#   set.seed(i)
# 
#   Fit_res_RIES <- phenologyFitter(
#   modelfn = PhenoFlex_GDHwrapper,
#   bloomJDays = Bergheim_pheno$pheno,
#   SeasonList = Bergheim_easy,
#   lower = lower,
#   upper = upper,
#   control = list(
#   smooth = FALSE,
#   verbose = TRUE,
#   maxit = 30,
#   nb.stop.improvement = 500
#   )
#   )
# 
# 
#   Bergheim_pheno$predicted <-
#   purrr::map_dbl(Bergheim_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
#   Bergheim_pheno$val <- 0
# 
# 
# 
#   Bordeaux_pheno$predicted <-
#   purrr::map_dbl(Bordeaux_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
#   Bordeaux_pheno$val <- 1
# 
#   PA_pheno$predicted <-
#   purrr::map_dbl(PA_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
#   PA_pheno$val <- 1
# 
#   Ontario_pheno$predicted <-
#   purrr::map_dbl(Ontario_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
#   Ontario_pheno$val <- 1
# 
#   LF_pheno$predicted <-
#   purrr::map_dbl(LF_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
#   LF_pheno$val <- 1
# 
#   MB_pheno$predicted <-
#   purrr::map_dbl(MB_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
#   MB_pheno$val <- 1
# 
#   Vassal_pheno$predicted <-
#   purrr::map_dbl(Vassal_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
#   Vassal_pheno$val <- 1
# 
#   riesling_pheno <- rbind(Bergheim_pheno,
#                          Vassal_pheno,
#                          MB_pheno,
#                          Bordeaux_pheno,
#                          LF_pheno,
#                          Ontario_pheno,
#                          PA_pheno)
#   a=RMSEP(riesling_pheno$predicted, riesling_pheno$pheno, na.rm = T)
# 
#   riesling_phenoval<- rbind(Vassal_pheno,
#                          MB_pheno,
#                          Bordeaux_pheno,
#                          LF_pheno,
#                          Ontario_pheno,
#                          PA_pheno)
#   b=RMSEP(riesling_phenoval$predicted, riesling_phenoval$pheno, na.rm = T)
# 
#   c=RMSEP(Bergheim_pheno$predicted, Bergheim_pheno$pheno, na.rm = T)
# 
# 
# 
#   RIES_model1=rbind(RIES_model1, c(i, a, b, c))
#   print(i)
# 
# }
# 
# 
# colnames(RIES_model1)=c("seed","RMSEall","RMSEval","RMSEcal")

# seed 25 produces lowest RMSEval = 6.99; RMSEall = 6.61; RMSEcal = 6.17

set.seed(25)
  
Fit_res_RIES <- phenologyFitter(
modelfn = PhenoFlex_GDHwrapper,
bloomJDays = Bergheim_pheno$pheno,
SeasonList = Bergheim_easy,
lower = lower,
upper = upper,
control = list(
smooth = FALSE,
verbose = TRUE,
maxit = 30,
nb.stop.improvement = 500
)
)


Bergheim_pheno$predicted <-
purrr::map_dbl(Bergheim_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
Bergheim_pheno$val <- 0



Bordeaux_pheno$predicted <-
purrr::map_dbl(Bordeaux_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
Bordeaux_pheno$val <- 1

PA_pheno$predicted <-
purrr::map_dbl(PA_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
PA_pheno$val <- 1

Ontario_pheno$predicted <-
purrr::map_dbl(Ontario_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
Ontario_pheno$val <- 1

LF_pheno$predicted <-
purrr::map_dbl(LF_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
LF_pheno$val <- 1

MB_pheno$predicted <-
purrr::map_dbl(MB_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
MB_pheno$val <- 1

Vassal_pheno$predicted <-
purrr::map_dbl(Vassal_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_RIES$model_fit$par))
Vassal_pheno$val <- 1

riesling_pheno <- rbind(Bergheim_pheno,
                       Vassal_pheno,
                       MB_pheno,
                       Bordeaux_pheno,
                       LF_pheno,
                       Ontario_pheno,
                       PA_pheno)
aRIES=RMSEP(riesling_pheno$predicted, riesling_pheno$pheno, na.rm = T)

riesling_phenoval<- rbind(Vassal_pheno,
                       MB_pheno,
                       Bordeaux_pheno,
                       LF_pheno,
                       Ontario_pheno,
                       PA_pheno)
bRIES=RMSEP(riesling_phenoval$predicted, riesling_phenoval$pheno, na.rm = T)

cRIES=RMSEP(Bergheim_pheno$predicted, Bergheim_pheno$pheno, na.rm = T)

dRIES=mean(riesling_pheno$predicted-riesling_pheno$pheno, na.rm = T)

eRIES=mean(riesling_phenoval$predicted-riesling_phenoval$pheno, na.rm = T)

fRIES=mean(Bergheim_pheno$predicted-Bergheim_pheno$pheno, na.rm = T)

aRIES #RMSEall
bRIES #RMSEval
cRIES #RMSEcal

dRIES #biasall
eRIES #biasval
fRIES #biascal

```


```{r All results from Method 1}

all_pheno <- rbind(cabsauv_phenoval,
                   riesling_phenoval)
RMSEP(all_pheno$predicted, all_pheno$pheno, na.rm = T)
# Overall RMSE for fitting in cold location  = 7.34
mean(all_pheno$predicted - all_pheno$pheno, na.rm = T)
# bias = 0.15


#Riesling results, method 1

aRIES #RMSEall
bRIES #RMSEval
cRIES #RMSEcal

dRIES #biasall
eRIES #biasval
fRIES #biascal


#Cab.-Sauvignon results, method 1

aCS #RMSEall
bCS #RMSEval
cCS #RMSEcal

dCS #biasall
eCS #biasval
fCS #biascal


```





# FIT ENTIRE DATASET

```{r Riesling - Method 2}
riesling.bb <- data.frame(riesling_pheno) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Cultivar == "Riesling") %>% arrange(Location, Year)



wdat.cal <- wdat3[!(wdat3$Location == "Portland_NY"),]
rownames(wdat.cal) <- NULL
wdat.cal <- droplevels(wdat.cal)


# modify the years so that each year is unique for each location 
# we have to do this procedure due to the way the weather data is read into the PhenologyFitter function (list of dataframes required, thus a given year cannot overlap for more than one location). Mike, let me know if you have any questions.

# bordeaux = no change
# colmar = +1000 (yrs will range from ~2050-3023)
# lewisberg = +2000
# lower franconia = +3000
# MB = +4000
# ontario = + 5000
# vassal = +6000

# modifying years for weather dataset
wdat.cal$yearmod <- wdat.cal$Year
wdat.cal$yearmod[wdat.cal$Location == "Colmar"] <- wdat.cal$Year[wdat.cal$Location == "Colmar"] + 1000
wdat.cal$yearmod[wdat.cal$Location == "Lewisberg_PA"] <- wdat.cal$Year[wdat.cal$Location == "Lewisberg_PA"] + 2000
wdat.cal$yearmod[wdat.cal$Location == "Lower_Franconia"] <- wdat.cal$Year[wdat.cal$Location == "Lower_Franconia"] + 3000
wdat.cal$yearmod[wdat.cal$Location == "MB"] <- wdat.cal$Year[wdat.cal$Location == "MB"] + 4000
wdat.cal$yearmod[wdat.cal$Location == "Ontario"] <- wdat.cal$Year[wdat.cal$Location == "Ontario"] + 5000
wdat.cal$yearmod[wdat.cal$Location == "Vassal"] <- wdat.cal$Year[wdat.cal$Location == "Vassal"] + 6000

# modifying years for phenology dataset
riesling.bb$yearmod <- riesling.bb$Year
riesling.bb$yearmod[riesling.bb$Location == "Colmar"] <- riesling.bb$Year[riesling.bb$Location == "Colmar"] + 1000
riesling.bb$yearmod[riesling.bb$Location == "Lewisberg_PA"] <- riesling.bb$Year[riesling.bb$Location == "Lewisberg_PA"] + 2000
riesling.bb$yearmod[riesling.bb$Location == "Lower_Franconia"] <- riesling.bb$Year[riesling.bb$Location == "Lower_Franconia"] + 3000
riesling.bb$yearmod[riesling.bb$Location == "MB"] <- riesling.bb$Year[riesling.bb$Location == "MB"] + 4000
riesling.bb$yearmod[riesling.bb$Location == "Ontario"] <- riesling.bb$Year[riesling.bb$Location == "Ontario"] + 5000
riesling.bb$yearmod[riesling.bb$Location == "Vassal"] <- riesling.bb$Year[riesling.bb$Location == "Vassal"] + 6000

names(wdat.cal)[names(wdat.cal) == "Year"] <- "True_Year"
names(wdat.cal)[names(wdat.cal) == "yearmod"] <- "Year"
names(wdat.cal)[names(wdat.cal) == "Temperature"] <- "Temp"

names(riesling.bb)[names(riesling.bb) == "Year"] <- "True_Year"
names(riesling.bb)[names(riesling.bb) == "yearmod"] <- "Year"

# now set calibration years and generate season list
riesling.calibration <- unique(riesling.bb$Year) # all years

riesling.SeasonList <- genSeasonList(wdat.cal, years = riesling.calibration)


upper <- c(42, 200, 1.0, 30, 4000.0, 10000.0, 7000.0, 6.e13, 10, 40, 10, 50.00)
lower <- c(39, 180, 0.1, 0 , 3000.0, 9000.0, 6000.0, 5.e13, 0, 0, 0, 0.05)

RIES_model2=data.frame(NULL)

#Only run to check parameters
# 
# for (i in 1:30) {
# 
#   set.seed(i)
# 
#   Fit_res_RIES2 <- phenologyFitter(
#   modelfn = PhenoFlex_GDHwrapper,
#   bloomJDays = riesling.bb$bb.doy[which(riesling.bb$Year %in% riesling.calibration)],
#   SeasonList = riesling.SeasonList,
#   lower = lower,
#   upper = upper,
#   control = list(
#   smooth = FALSE,
#   verbose = TRUE,
#   maxit = 30,
#   nb.stop.improvement = 500
#   )
#   )
# 
#   a=RMSEP(Fit_res_RIES2$pbloomJDays, Fit_res_RIES2$bloomJDays, na.rm = T)
# 
#   RIES_model2=rbind(RIES_model2, c(i,a))
#   print(i)
# 
# }
# 
# colnames(RIES_model2)=c("seed","RMSEall")

# seed 22 produces lowest RMSEall for Riesling


set.seed(22)

Fit_res_RIES2 <- phenologyFitter(
modelfn = PhenoFlex_GDHwrapper,
bloomJDays = riesling.bb$bb.doy[which(riesling.bb$Year %in% riesling.calibration)],
SeasonList = riesling.SeasonList,
lower = lower,
upper = upper,
control = list(
smooth = FALSE,
verbose = TRUE,
maxit = 30,
nb.stop.improvement = 500
)
)

riesling.predictions <- data.frame(riesling.bb)
riesling.predictions[["Predicted"]] <- Fit_res_RIES2$pbloomJDays
riesling.predictions$Year <- NULL
names(riesling.predictions)[names(riesling.predictions) == "True_Year"] <- "Year"
riesling_mod <- lm(Predicted ~ bb.doy, riesling.predictions)
summary(riesling_mod)
mean(riesling.predictions$Predicted - riesling.predictions$bb.doy)
```

```{r Cabernet Sauvignon - Method 2}
cabsauv.bb <- subset(bbdat, Cultivar == "Cabernet_Sauvignon")
cabsauv.bb <- droplevels(cabsauv.bb)
cabsauv.bb <- cabsauv.bb %>%
  filter(!(BBCH.scale %in% c("5")))

wdat.cal <- subset(wdat3, Location %in% c("MB", "Bordeaux", "Vassal", "Colmar"))
wdat.cal <- droplevels(wdat.cal)
rownames(wdat.cal) <- NULL

# modify the years so that each year is unique for each location 
# bordeaux = no change
# colmar = +1000 (yrs will range from ~2050-3023)
# lewisberg = +2000
# lower franconia = +3000
# MB = +4000
# ontario = + 5000
# vassal = +6000

# modifying years for weather dataset
wdat.cal$yearmod <- wdat.cal$Year
wdat.cal$yearmod[wdat.cal$Location == "Colmar"] <- wdat.cal$Year[wdat.cal$Location == "Colmar"] + 1000
wdat.cal$yearmod[wdat.cal$Location == "MB"] <- wdat.cal$Year[wdat.cal$Location == "MB"] + 4000
wdat.cal$yearmod[wdat.cal$Location == "Vassal"] <- wdat.cal$Year[wdat.cal$Location == "Vassal"] + 6000

# modifying years for phenology dataset
cabsauv.bb$yearmod <- cabsauv.bb$Year
cabsauv.bb$yearmod[cabsauv.bb$Location == "Colmar"] <- cabsauv.bb$Year[cabsauv.bb$Location == "Colmar"] + 1000
cabsauv.bb$yearmod[cabsauv.bb$Location == "MB"] <- cabsauv.bb$Year[cabsauv.bb$Location == "MB"] + 4000
cabsauv.bb$yearmod[cabsauv.bb$Location == "Vassal"] <- cabsauv.bb$Year[cabsauv.bb$Location == "Vassal"] + 6000

names(wdat.cal)[names(wdat.cal) == "Year"] <- "True_Year"
names(wdat.cal)[names(wdat.cal) == "yearmod"] <- "Year"
names(wdat.cal)[names(wdat.cal) == "Temperature"] <- "Temp"

names(cabsauv.bb)[names(cabsauv.bb) == "Year"] <- "True_Year"
names(cabsauv.bb)[names(cabsauv.bb) == "yearmod"] <- "Year"

# now set calibration years and generate season list
cabsauv.calibration <- unique(cabsauv.bb$Year) # all years

cabsauv.SeasonList <- genSeasonList(wdat.cal, years = cabsauv.calibration)

upper <- c(42, 200, 1.0, 30, 4000.0, 10000.0, 7000.0, 6.e13, 10, 40, 10, 50.00)
lower <- c(39, 180, 0.1, 0 , 3000.0, 9000.0, 6000.0, 5.e13, 0, 0, 0, 0.05)


CS_model2=data.frame(NULL)

# Only run to check parameters
# 
# for (i in 1:30) {
# 
#   set.seed(i)
# 
# 
#   Fit_res_CS2 <- phenologyFitter(
#   modelfn = PhenoFlex_GDHwrapper,
#   bloomJDays = cabsauv.bb$bb.doy[which(cabsauv.bb$Year %in% cabsauv.calibration)],
#   SeasonList = cabsauv.SeasonList,
#   lower = lower,
#   upper = upper,
#   control = list(
#   smooth = FALSE,
#   verbose = TRUE,
#   maxit = 30,
#   nb.stop.improvement = 500
#   )
#   )
# 
#   a=RMSEP(Fit_res_CS2$pbloomJDays, Fit_res_CS2$bloomJDays, na.rm = T)
# 
#   CS_model2=rbind(CS_model2, c(i,a))
# 
#   print(i)
# 
# }
# 
# 
# colnames(CS_model2)=c("seed","RMSEall")
# 

# seed 15 produces lowest RMSEall for Cab-Sauv


set.seed(15)


Fit_res_CS2 <- phenologyFitter(
modelfn = PhenoFlex_GDHwrapper,
bloomJDays = cabsauv.bb$bb.doy[which(cabsauv.bb$Year %in% cabsauv.calibration)],
SeasonList = cabsauv.SeasonList,
lower = lower,
upper = upper,
control = list(
smooth = FALSE,
verbose = TRUE,
maxit = 30,
nb.stop.improvement = 500
)
)
  

cabsauv.predictions <- data.frame(cabsauv.bb)
cabsauv.predictions[["Predicted"]] <- Fit_res_CS2$pbloomJDays
cabsauv.predictions$Year <- NULL
names(cabsauv.predictions)[names(cabsauv.predictions) == "True_Year"] <- "Year"
cabsauv_mod <- lm(Predicted ~ bb.doy, cabsauv.predictions)
summary(cabsauv_mod)
mean(cabsauv.predictions$Predicted - cabsauv.predictions$bb.doy)
```

```{r Concord - Method 2}

# Extracting Phenology datasets #

Portland_pheno <- data.frame(bbdat) %>%
dplyr::select(bb.date, Year, bb.doy, Location, BBCH.scale, Dataset, Cultivar, Observer) %>%
mutate(pheno = as.numeric(bb.doy)) %>%
filter(
Location == "Portland_NY",
#BBCH.scale %in% c(7),
Cultivar == "Concord") %>% arrange(Location, Year)

pheno_years_Portland <- unique(Portland_pheno$Year)

# Prepare temperature datasets #

wdat.Portland <- subset(wdat2, Location %in% "Portland_NY")

Portland_easy <- data.frame(wdat.Portland) %>%
mutate(
Year = year(Date),
Month = month(Date),
Day = day(Date)
) %>%
stack_hourly_temps(latitude = unique(.$Latitude)) %>%
pluck(1) %>%
genSeasonList(mrange = c(8, 6),
years = pheno_years_Portland)

# parameterize phenoflex w Portland NY data #

upper <- c(42, 200, 1.0, 30, 4000.0, 10000.0, 7000.0, 6.e13, 10, 40, 10, 50.00)
lower <- c(39, 180, 0.1, 0 , 3000.0, 9000.0, 6000.0, 5.e13, 0, 0, 0, 0.05)

CON_model2=data.frame(NULL)

# Only run to check parameters
# 
# for (i in 1:30) {
# 
#   set.seed(i)
# 
#   Fit_res_CON <- phenologyFitter(
#   modelfn = PhenoFlex_GDHwrapper,
#   bloomJDays = Portland_pheno$pheno,
#   SeasonList = Portland_easy,
#   lower = lower,
#   upper = upper,
#   control = list(
#   smooth = FALSE,
#   verbose = TRUE,
#   maxit = 30,
#   nb.stop.improvement = 500
#   )
#   )
# 
# 
#   Portland_pheno$predicted <-
#   purrr::map_dbl(Portland_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CON$model_fit$par))
#   Portland_pheno$val <- 0
#   a=RMSEP(Portland_pheno$predicted, Portland_pheno$pheno, na.rm = T)
# 
#   CON_model2=rbind(CON_model2, c(i,a))
#   print(i)
# }
# 
# colnames(CON_model2)=c("seed","RMSEcal")

# seed 15 produces lowest RMSEcal=4.56


set.seed(15)

Fit_res_CON <- phenologyFitter(
modelfn = PhenoFlex_GDHwrapper,
bloomJDays = Portland_pheno$pheno,
SeasonList = Portland_easy,
lower = lower,
upper = upper,
control = list(
smooth = FALSE,
verbose = TRUE,
maxit = 30,
nb.stop.improvement = 500
)
)

Portland_pheno$Predicted <-
purrr::map_dbl(Portland_easy,~ PhenoFlex_GDHwrapper(.x, Fit_res_CON$model_fit$par))
Portland_pheno$val <- 0

```


```{r All results from Method 2}

all_CON_method2=data.frame(Portland_pheno$Cultivar,Portland_pheno$Dataset, Portland_pheno$bb.doy,Portland_pheno$Predicted)

colnames(all_CON_method2)=c("Cultivar","Dataset","bb.doy","Predicted")


all_RIES_method2=data.frame(riesling.predictions$Cultivar,riesling.predictions$Dataset, riesling.predictions$bb.doy,riesling.predictions$Predicted)               

colnames(all_RIES_method2)=c("Cultivar","Dataset","bb.doy","Predicted")        


all_CS_method2=data.frame(cabsauv.predictions$Cultivar,cabsauv.predictions$Dataset, cabsauv.predictions$bb.doy,cabsauv.predictions$Predicted)               

colnames(all_CS_method2)=c("Cultivar","Dataset","bb.doy","Predicted")  


all_pheno_fullfit <- rbind(all_CS_method2,
                   all_RIES_method2,
                   all_CON_method2)
RMSEP(all_pheno_fullfit$Predicted, all_pheno_fullfit$bb.doy, na.rm = T)
mean(all_pheno_fullfit$Predicted - all_pheno_fullfit$bb.doy, na.rm = T)
fullfit_mod <- lm(Predicted ~ bb.doy, data = all_pheno_fullfit)
summary(fullfit_mod)
#summary(all_pheno_mod)
#plot(all_pheno_fullfit$Predicted, all_pheno_fullfit$bb.doy)
```




```{r supplementary figure plots}

pal2=c( "#C32966","#234F9C", "#3B8441")
pal2b=c( "#C32966", "#3B8441")

#### Method 1 - Phenoflex fit on cold location only####

all_pheno=rbind(cabsauv_pheno, riesling_pheno)

circle = c("0" = 19, "1" = 21)

all_cold <- ggplot(data=all_pheno)+
  geom_abline(slope=1,intercept = 0, lty=1, linewidth=0.3)+
  geom_point(aes(x=pheno,y=predicted, color=Cultivar, shape = as.factor(val)))+
  geom_smooth(aes(x=pheno,y=predicted, lty=as.factor(val)), col="black",fill="black",method="lm")+
  scale_color_manual(values=pal2b)+
  scale_fill_manual(values=pal2b)+
  scale_shape_manual(values = circle)+
  scale_y_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  scale_x_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  ylab("") + xlab("") + labs(color="Cultivar", fill="Cultivar")+
  theme_bw(base_size=8) +
  #facet_wrap(.~Cultivar)+
  theme(legend.position = "none",
        strip.background = element_rect(color="#CCCCCC"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line.x = element_line(linewidth=0.1,color="black"),
        axis.line.y = element_line(linewidth=0.1,color="black"),
        axis.text = element_text(size=8, color="black"),
        axis.ticks = element_line(linewidth=0.1,color="black"),
        axis.ticks.length = unit(0.2, 'lines'),
        axis.text.x = element_text(angle=0,vjust=0, hjust=0.5),
        aspect.ratio = 1)


riesling_cold <- ggplot(data=riesling_pheno)+
  geom_abline(slope=1,intercept = 0, lty=1, linewidth=0.3)+
 geom_smooth(aes(x=pheno,y=predicted), color="#3B8441",fill="#3B8441",method="lm")+
  geom_point(aes(x=pheno,y=predicted, shape = as.factor(val)), color="#3B8441")+
  scale_color_manual(values=pal2)+
  scale_fill_manual(values=pal2)+
  scale_shape_manual(values = circle)+
  scale_y_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  scale_x_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  ylab("") + xlab("") + labs(color="Cultivar", fill="Cultivar")+
  theme_bw(base_size=8) +
  #facet_wrap(.~Cultivar)+
  theme(legend.position = "none",
        strip.background = element_rect(color="#CCCCCC"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line.x = element_line(linewidth=0.1,color="black"),
        axis.line.y = element_line(linewidth=0.1,color="black"),
        axis.text = element_text(size=8, color="black"),
        axis.ticks = element_line(linewidth=0.1,color="black"),
        axis.ticks.length = unit(0.2, 'lines'),
        axis.text.x = element_blank(),
        aspect.ratio = 1)

cabsauv_cold <- ggplot(data=cabsauv_pheno)+
  geom_abline(slope=1,intercept = 0, lty=1, linewidth=0.3)+
 geom_smooth(aes(x=pheno,y=predicted), color="#C32966",fill="#C32966",method="lm")+
  geom_point(aes(x=pheno,y=predicted, shape = as.factor(val)), color="#C32966")+
  scale_color_manual(values=pal2)+
  scale_fill_manual(values=pal2)+
  scale_shape_manual(values = circle)+
  scale_y_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  scale_x_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  ylab("") + xlab("") + labs(color="Cultivar", fill="Cultivar")+
  theme_bw(base_size=8) +
  #facet_wrap(.~Cultivar)+
  theme(legend.position = "none",
        strip.background = element_rect(color="#CCCCCC"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line.x = element_line(linewidth=0.1,color="black"),
        axis.line.y = element_line(linewidth=0.1,color="black"),
        axis.text = element_text(size=8, color="black"),
        axis.ticks = element_line(linewidth=0.1,color="black"),
        axis.ticks.length = unit(0.2, 'lines'),
        axis.text.x = element_blank(),
        aspect.ratio = 1)

all_plots_cold <- cabsauv_cold / riesling_cold
all_cold+all_plots_cold

#Stats for all data

#RMSE val
RMSEP(all_pheno$predicted[all_pheno$val==1], all_pheno$pheno[all_pheno$val==1], na.rm = T)
#bias val
mean(all_pheno$predicted[all_pheno$val==1] - all_pheno$pheno[all_pheno$val==1], na.rm = T)
#r2 val
(cor(all_pheno$predicted[all_pheno$val==1], all_pheno$pheno[all_pheno$val==1]))^2

length(all_pheno$predicted[all_pheno$val==1])

#RMSE cal
RMSEP(all_pheno$predicted[all_pheno$val==0], all_pheno$pheno[all_pheno$val==0], na.rm = T)
#bias cal
mean(all_pheno$predicted[all_pheno$val==0] - all_pheno$pheno[all_pheno$val==0], na.rm = T)
#r2 cal
(cor(all_pheno$predicted[all_pheno$val==0], all_pheno$pheno[all_pheno$val==0]))^2


#Stats for each cultivar

# Cab-Sauv

#RMSE val
RMSEP(cabsauv_pheno$predicted[cabsauv_pheno$val==1], cabsauv_pheno$pheno[cabsauv_pheno$val==1], na.rm = T)
#bias val
mean(cabsauv_pheno$predicted[cabsauv_pheno$val==1] - cabsauv_pheno$pheno[cabsauv_pheno$val==1], na.rm = T)
#r2 val
(cor(cabsauv_pheno$predicted[cabsauv_pheno$val==1], cabsauv_pheno$pheno[cabsauv_pheno$val==1]))^2

length(cabsauv_pheno$predicted[cabsauv_pheno$val==1])

#RMSE cal
RMSEP(cabsauv_pheno$predicted[cabsauv_pheno$val==0], cabsauv_pheno$pheno[cabsauv_pheno$val==0], na.rm = T)
#bias cal
mean(cabsauv_pheno$predicted[cabsauv_pheno$val==0] - cabsauv_pheno$pheno[cabsauv_pheno$val==0], na.rm = T)
#r2 cal
(cor(cabsauv_pheno$predicted[cabsauv_pheno$val==0], cabsauv_pheno$pheno[cabsauv_pheno$val==0]))^2

length(cabsauv_pheno$predicted[cabsauv_pheno$val==0])


# Riesling

#RMSE val
RMSEP(riesling_pheno$predicted[riesling_pheno$val==1], riesling_pheno$pheno[riesling_pheno$val==1], na.rm = T)
#bias val
mean(riesling_pheno$predicted[riesling_pheno$val==1] - riesling_pheno$pheno[riesling_pheno$val==1], na.rm = T)
#r2 val
(cor(riesling_pheno$predicted[riesling_pheno$val==1], riesling_pheno$pheno[riesling_pheno$val==1]))^2

length(riesling_pheno$predicted[riesling_pheno$val==1])

#RMSE cal
RMSEP(riesling_pheno$predicted[riesling_pheno$val==0], riesling_pheno$pheno[riesling_pheno$val==0], na.rm = T)
#bias cal
mean(riesling_pheno$predicted[riesling_pheno$val==0] - riesling_pheno$pheno[riesling_pheno$val==0], na.rm = T)
#r2 cal
(cor(riesling_pheno$predicted[riesling_pheno$val==0], riesling_pheno$pheno[riesling_pheno$val==0]))^2

length(riesling_pheno$predicted[riesling_pheno$val==0])



# ggsave("all_plots_cold.pdf", plot=all_plots_cold, width=3, height=9, units =c("in"), dpi=300)
# ggsave("all_cold.pdf", plot=all_cold, width=9, height=9, units =c("in"), dpi=300)



#### Method 2 - PhenoFlex fit on entire dataset ####


fullfit_all <- ggplot(data=all_pheno_fullfit)+
  geom_abline(slope=1,intercept = 0, lty=1, linewidth=0.3)+
  geom_point(aes(x=bb.doy,y=Predicted, color=Cultivar))+
  geom_smooth(aes(x=bb.doy,y=Predicted), col="black",fill="black",method="lm")+
  scale_color_manual(values=pal2)+
  scale_fill_manual(values=pal2)+
  scale_y_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  scale_x_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  ylab("") + xlab("") +
  theme_bw(base_size=8) +
  #facet_wrap(.~Cultivar)+
  theme(legend.position = "none",
        strip.background = element_rect(color="#CCCCCC"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line.x = element_line(linewidth=0.1,color="black"),
        axis.line.y = element_line(linewidth=0.1,color="black"),
        axis.text = element_text(size=8, color="black"),
        axis.ticks = element_line(linewidth=0.1,color="black"),
        axis.ticks.length = unit(0.2, 'lines'),
        axis.text.x = element_text(angle=0,vjust=0, hjust=0.5),
        aspect.ratio = 1)

fullfit_concord <- ggplot(data=subset(all_pheno_fullfit, Cultivar %in% "Concord"))+
  geom_abline(slope=1,intercept = 0, lty=1, linewidth=0.3)+
 geom_smooth(aes(x=bb.doy,y=Predicted), color="#234F9C",fill="#234F9C",method="lm")+
  geom_point(aes(x=bb.doy,y=Predicted), color="#234F9C")+
  scale_color_manual(values=pal2)+
  scale_fill_manual(values=pal2)+
  scale_y_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  scale_x_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  ylab("") + xlab("") + 
  theme_bw(base_size=8) +
  #facet_wrap(.~Cultivar)+
  theme(legend.position = "none",
        strip.background = element_rect(color="#CCCCCC"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line.x = element_line(linewidth=0.1,color="black"),
        axis.line.y = element_line(linewidth=0.1,color="black"),
        axis.text = element_text(size=8, color="black"),
        axis.ticks = element_line(linewidth=0.1,color="black"),
        axis.ticks.length = unit(0.2, 'lines'),
        axis.text.x = element_text(angle=45,vjust=0, hjust=0.5),
        aspect.ratio = 1)


fullfit_riesling <- ggplot(data=subset(all_pheno_fullfit, Cultivar %in% "Riesling"))+
  geom_abline(slope=1,intercept = 0, lty=1, linewidth=0.3)+
 geom_smooth(aes(x=bb.doy,y=Predicted), color="#3B8441",fill="#3B8441",method="lm")+
  geom_point(aes(x=bb.doy,y=Predicted), color="#3B8441")+
  scale_color_manual(values=pal2)+
  scale_fill_manual(values=pal2)+
  scale_y_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  scale_x_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  ylab("") + xlab("") + labs(color="Cultivar", fill="Cultivar")+
  theme_bw(base_size=8) +
  #facet_wrap(.~Cultivar)+
  theme(legend.position = "none",
        strip.background = element_rect(color="#CCCCCC"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line.x = element_line(linewidth=0.1,color="black"),
        axis.line.y = element_line(linewidth=0.1,color="black"),
        axis.text = element_text(size=8, color="black"),
        axis.ticks = element_line(linewidth=0.1,color="black"),
        axis.ticks.length = unit(0.2, 'lines'),
        axis.text.x = element_blank(),
        aspect.ratio = 1)

fullfit_cabsauv <- ggplot(data=subset(all_pheno_fullfit, Cultivar %in% "Cabernet_Sauvignon"))+
  geom_abline(slope=1,intercept = 0, lty=1, linewidth=0.3)+
 geom_smooth(aes(x=bb.doy,y=Predicted), color="#C32966",fill="#C32966",method="lm")+
  geom_point(aes(x=bb.doy,y=Predicted), color="#C32966")+
  scale_color_manual(values=pal2)+
  scale_fill_manual(values=pal2)+
  scale_y_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  scale_x_continuous(limits=c(40,160), breaks=seq(40,160,20))+
  ylab("") + xlab("") + labs(color="Cultivar", fill="Cultivar")+
  theme_bw(base_size=8) +
  #facet_wrap(.~Cultivar)+
  theme(legend.position = "none",
        strip.background = element_rect(color="#CCCCCC"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line.x = element_line(linewidth=0.1,color="black"),
        axis.line.y = element_line(linewidth=0.1,color="black"),
        axis.text = element_text(size=8, color="black"),
        axis.ticks = element_line(linewidth=0.1,color="black"),
        axis.ticks.length = unit(0.2, 'lines'),
        axis.text.x = element_blank(),
        aspect.ratio = 1)

all_plots_fullfit <- fullfit_cabsauv / fullfit_riesling / fullfit_concord
fullfit_all + all_plots_fullfit


# Stats for method 2

# All data

#RMSE val
RMSEP(all_pheno_fullfit$Predicted, all_pheno_fullfit$bb.doy, na.rm = T)
#bias val
mean(all_pheno_fullfit$Predicted-all_pheno_fullfit$bb.doy, na.rm = T)
#r2 val
(cor(all_pheno_fullfit$Predicted, all_pheno_fullfit$bb.doy))^2

# Cab-Sauv
csall_pheno_fullfit=subset(all_pheno_fullfit, Cultivar %in% "Cabernet_Sauvignon")

#RMSE val
RMSEP(csall_pheno_fullfit$Predicted, csall_pheno_fullfit$bb.doy, na.rm = T)
#bias val
mean(csall_pheno_fullfit$Predicted-csall_pheno_fullfit$bb.doy, na.rm = T)
#r2 val
(cor(csall_pheno_fullfit$Predicted, csall_pheno_fullfit$bb.doy))^2


# Riesling
riesall_pheno_fullfit=subset(all_pheno_fullfit, Cultivar %in% "Riesling")

#RMSE val
RMSEP(riesall_pheno_fullfit$Predicted, riesall_pheno_fullfit$bb.doy, na.rm = T)
#bias val
mean(riesall_pheno_fullfit$Predicted-riesall_pheno_fullfit$bb.doy, na.rm = T)
#r2 val
(cor(riesall_pheno_fullfit$Predicted, riesall_pheno_fullfit$bb.doy))^2


# Concord
conall_pheno_fullfit=subset(all_pheno_fullfit, Cultivar %in% "Concord")

#RMSE val
RMSEP(conall_pheno_fullfit$Predicted, conall_pheno_fullfit$bb.doy, na.rm = T)
#bias val
mean(conall_pheno_fullfit$Predicted-conall_pheno_fullfit$bb.doy, na.rm = T)
#r2 val
(cor(conall_pheno_fullfit$Predicted, conall_pheno_fullfit$bb.doy))^2







# ggsave("all_plots_fullfit.pdf", plot=all_plots_fullfit, width=3, height=9, units =c("in"), dpi=300)
# ggsave("fullfit_all.pdf", plot=fullfit_all, width=9, height=9, units =c("in"), dpi=300)

```
